# Base image
FROM node:10.17

# Set working directory
RUN mkdir -p /usr/src/frontend-client
WORKDIR /usr/src/frontend-client

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/frontend-client/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY ./package.json /usr/src/frontend-client/
RUN npm install --silent
RUN npm install -g @angular/cli@8.3.8

# Start app
CMD ng serve --host 0.0.0.0 -o

